-- CreateTable
CREATE TABLE `learner_lifecycles` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_id` INTEGER NOT NULL,
    `brand_id` INTEGER NOT NULL,
    `current_status` ENUM('PENDING_PAYMENT', 'ENROLLED', 'ONBOARDING', 'ASSESSMENT', 'ACTIVE_DSA', 'DSA_REVIEW', 'ACTIVE_SYSTEM_DESIGN', 'READY_FOR_PLACEMENT', 'PLACEMENT_ACTIVE', 'COMPLETED', 'PAUSED', 'OFFBOARDED', 'REFUNDED', 'LAPSED') NOT NULL DEFAULT 'PENDING_PAYMENT',
    `status_updated_at` DATETIME(3) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
